# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: ~/rush
    docker:
      - image: rushlang/rush-ci-x86-64-linux-gnu
    steps:
      - checkout
      - run:
          name: "Creating Build Files"
          command: |
            mkdir -p ~/rush/build &&
            cd ~/rush/build &&
            cmake ../ \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_PREFIX_PATH=/opt/llvm
      - run:
          name: "Building Binary Files"
          command: |
            cd ~/rush/build
            cmake --build . -j 2
            ./crush --version
      - run:
          name: "Executing Unit Test"
          command: |
            cd ~/rush/build
            ctest --output-on-failure

